### ISSUE TITLE
Missing database directory after upgrade

### ISSUE THREAD

**Issue by Armag67** [blooser/youtube-downloader#1]
Hello,
After upgrade on my manjaro box with `pip install --upgrade youtube-downloader`, I have this traceback at launch of `youtube-downloader`:
```
Traceback (most recent call last):
  File "/home/h2/.local/bin/youtube-downloader", line 5, in <module>
    from youtubedownloader import main
  File "/home/h2/.local/lib/python3.8/site-packages/youtubedownloader/__init__.py", line 24, in <module>
    from .models import (
  File "/home/h2/.local/lib/python3.8/site-packages/youtubedownloader/models.py", line 9, in <module>
    from .database.models import History
ModuleNotFoundError: No module named 'youtubedownloader.database'
```
And actually the directory:
`/home/h2/.local/lib/python3.8/site-packages/youtubedownloader/database`  doesn't exist.
I needed to create this `database` directory and populate him with his two files (`__init__.py` and `models.py`) picked manually on your GitHub repository and now all is working like a charm.

**Comment by blooser** [comment]
Hello!

Thank you for the issue.

I'm sorry it looks like I've forgotten to add the database module into `setup.py`

The 04104234eb9a9b0ce617fdf843ea929fb68457bb should solve the problem.
